<?php

namespace AppBundle\Entity;

/**
 * AppRoleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AppRoleRepository extends \Doctrine\ORM\EntityRepository
{
}
