<?php

namespace AppBundle\Entity;

/**
 * AppUserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AppUserRepository extends \Doctrine\ORM\EntityRepository
{
}
